services:
  names:
    build: .
    command: ["python", "main.py", "name", "--port", "5000"]
    networks:
      - sdwb
    ports:
      - "5000:5000"

  client:
    build: .
    command: ["python", "main.py", "client", "--name-service", "names:5000", "--advertise-ip", "auto"]
    depends_on:
      - names
    environment:
      DISPLAY: ${DISPLAY:-host.docker.internal:0.0}
      SDWB_NAME_SERVICE: names:5000
      SDWB_ADVERTISE_IP: auto
    networks:
      - sdwb

networks:
  sdwb:
    driver: bridge
