# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sdwb_pb2 as sdwb__pb2


class NameDiscoveryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterCoordinator = channel.unary_unary(
                '/sdwb.NameDiscoveryService/RegisterCoordinator',
                request_serializer=sdwb__pb2.RegisterRequest.SerializeToString,
                response_deserializer=sdwb__pb2.RegisterResponse.FromString,
                )
        self.GetBoards = channel.unary_unary(
                '/sdwb.NameDiscoveryService/GetBoards',
                request_serializer=sdwb__pb2.Empty.SerializeToString,
                response_deserializer=sdwb__pb2.BoardListResponse.FromString,
                )


class NameDiscoveryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterCoordinator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBoards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NameDiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterCoordinator': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCoordinator,
                    request_deserializer=sdwb__pb2.RegisterRequest.FromString,
                    response_serializer=sdwb__pb2.RegisterResponse.SerializeToString,
            ),
            'GetBoards': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBoards,
                    request_deserializer=sdwb__pb2.Empty.FromString,
                    response_serializer=sdwb__pb2.BoardListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdwb.NameDiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NameDiscoveryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterCoordinator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdwb.NameDiscoveryService/RegisterCoordinator',
            sdwb__pb2.RegisterRequest.SerializeToString,
            sdwb__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBoards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdwb.NameDiscoveryService/GetBoards',
            sdwb__pb2.Empty.SerializeToString,
            sdwb__pb2.BoardListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class BoardCoordinatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinBoard = channel.unary_unary(
                '/sdwb.BoardCoordinatorService/JoinBoard',
                request_serializer=sdwb__pb2.JoinRequest.SerializeToString,
                response_deserializer=sdwb__pb2.JoinResponse.FromString,
                )
        self.SendAction = channel.unary_unary(
                '/sdwb.BoardCoordinatorService/SendAction',
                request_serializer=sdwb__pb2.ActionRequest.SerializeToString,
                response_deserializer=sdwb__pb2.ActionResponse.FromString,
                )
        self.GetSnapshot = channel.unary_unary(
                '/sdwb.BoardCoordinatorService/GetSnapshot',
                request_serializer=sdwb__pb2.Empty.SerializeToString,
                response_deserializer=sdwb__pb2.SnapshotResponse.FromString,
                )
        self.Ping = channel.unary_unary(
                '/sdwb.BoardCoordinatorService/Ping',
                request_serializer=sdwb__pb2.Empty.SerializeToString,
                response_deserializer=sdwb__pb2.Empty.FromString,
                )
        self.StartElection = channel.unary_unary(
                '/sdwb.BoardCoordinatorService/StartElection',
                request_serializer=sdwb__pb2.ElectionMessage.SerializeToString,
                response_deserializer=sdwb__pb2.ElectionResponse.FromString,
                )


class BoardCoordinatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinBoard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartElection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BoardCoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinBoard': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinBoard,
                    request_deserializer=sdwb__pb2.JoinRequest.FromString,
                    response_serializer=sdwb__pb2.JoinResponse.SerializeToString,
            ),
            'SendAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAction,
                    request_deserializer=sdwb__pb2.ActionRequest.FromString,
                    response_serializer=sdwb__pb2.ActionResponse.SerializeToString,
            ),
            'GetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshot,
                    request_deserializer=sdwb__pb2.Empty.FromString,
                    response_serializer=sdwb__pb2.SnapshotResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=sdwb__pb2.Empty.FromString,
                    response_serializer=sdwb__pb2.Empty.SerializeToString,
            ),
            'StartElection': grpc.unary_unary_rpc_method_handler(
                    servicer.StartElection,
                    request_deserializer=sdwb__pb2.ElectionMessage.FromString,
                    response_serializer=sdwb__pb2.ElectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdwb.BoardCoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BoardCoordinatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinBoard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdwb.BoardCoordinatorService/JoinBoard',
            sdwb__pb2.JoinRequest.SerializeToString,
            sdwb__pb2.JoinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdwb.BoardCoordinatorService/SendAction',
            sdwb__pb2.ActionRequest.SerializeToString,
            sdwb__pb2.ActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdwb.BoardCoordinatorService/GetSnapshot',
            sdwb__pb2.Empty.SerializeToString,
            sdwb__pb2.SnapshotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdwb.BoardCoordinatorService/Ping',
            sdwb__pb2.Empty.SerializeToString,
            sdwb__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartElection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdwb.BoardCoordinatorService/StartElection',
            sdwb__pb2.ElectionMessage.SerializeToString,
            sdwb__pb2.ElectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ClientUpdateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrepareAction = channel.unary_unary(
                '/sdwb.ClientUpdateService/PrepareAction',
                request_serializer=sdwb__pb2.ActionRequest.SerializeToString,
                response_deserializer=sdwb__pb2.VoteResponse.FromString,
                )
        self.CommitAction = channel.unary_unary(
                '/sdwb.ClientUpdateService/CommitAction',
                request_serializer=sdwb__pb2.ActionRequest.SerializeToString,
                response_deserializer=sdwb__pb2.Empty.FromString,
                )
        self.AbortAction = channel.unary_unary(
                '/sdwb.ClientUpdateService/AbortAction',
                request_serializer=sdwb__pb2.ActionRequest.SerializeToString,
                response_deserializer=sdwb__pb2.Empty.FromString,
                )
        self.GetLocalSnapshot = channel.unary_unary(
                '/sdwb.ClientUpdateService/GetLocalSnapshot',
                request_serializer=sdwb__pb2.Empty.SerializeToString,
                response_deserializer=sdwb__pb2.SnapshotResponse.FromString,
                )


class ClientUpdateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PrepareAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocalSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientUpdateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrepareAction': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareAction,
                    request_deserializer=sdwb__pb2.ActionRequest.FromString,
                    response_serializer=sdwb__pb2.VoteResponse.SerializeToString,
            ),
            'CommitAction': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitAction,
                    request_deserializer=sdwb__pb2.ActionRequest.FromString,
                    response_serializer=sdwb__pb2.Empty.SerializeToString,
            ),
            'AbortAction': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortAction,
                    request_deserializer=sdwb__pb2.ActionRequest.FromString,
                    response_serializer=sdwb__pb2.Empty.SerializeToString,
            ),
            'GetLocalSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocalSnapshot,
                    request_deserializer=sdwb__pb2.Empty.FromString,
                    response_serializer=sdwb__pb2.SnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdwb.ClientUpdateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClientUpdateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PrepareAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdwb.ClientUpdateService/PrepareAction',
            sdwb__pb2.ActionRequest.SerializeToString,
            sdwb__pb2.VoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CommitAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdwb.ClientUpdateService/CommitAction',
            sdwb__pb2.ActionRequest.SerializeToString,
            sdwb__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AbortAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdwb.ClientUpdateService/AbortAction',
            sdwb__pb2.ActionRequest.SerializeToString,
            sdwb__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLocalSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sdwb.ClientUpdateService/GetLocalSnapshot',
            sdwb__pb2.Empty.SerializeToString,
            sdwb__pb2.SnapshotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
