# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sdwb_pb2 as sdwb__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sdwb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NameDiscoveryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterCoordinator = channel.unary_unary(
                '/sdwb.NameDiscoveryService/RegisterCoordinator',
                request_serializer=sdwb__pb2.RegisterRequest.SerializeToString,
                response_deserializer=sdwb__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.GetBoards = channel.unary_unary(
                '/sdwb.NameDiscoveryService/GetBoards',
                request_serializer=sdwb__pb2.Empty.SerializeToString,
                response_deserializer=sdwb__pb2.BoardListResponse.FromString,
                _registered_method=True)


class NameDiscoveryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterCoordinator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBoards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NameDiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterCoordinator': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCoordinator,
                    request_deserializer=sdwb__pb2.RegisterRequest.FromString,
                    response_serializer=sdwb__pb2.RegisterResponse.SerializeToString,
            ),
            'GetBoards': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBoards,
                    request_deserializer=sdwb__pb2.Empty.FromString,
                    response_serializer=sdwb__pb2.BoardListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdwb.NameDiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sdwb.NameDiscoveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NameDiscoveryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterCoordinator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.NameDiscoveryService/RegisterCoordinator',
            sdwb__pb2.RegisterRequest.SerializeToString,
            sdwb__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBoards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.NameDiscoveryService/GetBoards',
            sdwb__pb2.Empty.SerializeToString,
            sdwb__pb2.BoardListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BoardCoordinatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinBoard = channel.unary_unary(
                '/sdwb.BoardCoordinatorService/JoinBoard',
                request_serializer=sdwb__pb2.JoinRequest.SerializeToString,
                response_deserializer=sdwb__pb2.JoinResponse.FromString,
                _registered_method=True)
        self.SendAction = channel.unary_unary(
                '/sdwb.BoardCoordinatorService/SendAction',
                request_serializer=sdwb__pb2.ActionRequest.SerializeToString,
                response_deserializer=sdwb__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.GetSnapshot = channel.unary_unary(
                '/sdwb.BoardCoordinatorService/GetSnapshot',
                request_serializer=sdwb__pb2.Empty.SerializeToString,
                response_deserializer=sdwb__pb2.SnapshotResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/sdwb.BoardCoordinatorService/Ping',
                request_serializer=sdwb__pb2.Empty.SerializeToString,
                response_deserializer=sdwb__pb2.Empty.FromString,
                _registered_method=True)
        self.StartElection = channel.unary_unary(
                '/sdwb.BoardCoordinatorService/StartElection',
                request_serializer=sdwb__pb2.ElectionMessage.SerializeToString,
                response_deserializer=sdwb__pb2.ElectionResponse.FromString,
                _registered_method=True)


class BoardCoordinatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinBoard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartElection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BoardCoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinBoard': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinBoard,
                    request_deserializer=sdwb__pb2.JoinRequest.FromString,
                    response_serializer=sdwb__pb2.JoinResponse.SerializeToString,
            ),
            'SendAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAction,
                    request_deserializer=sdwb__pb2.ActionRequest.FromString,
                    response_serializer=sdwb__pb2.ActionResponse.SerializeToString,
            ),
            'GetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshot,
                    request_deserializer=sdwb__pb2.Empty.FromString,
                    response_serializer=sdwb__pb2.SnapshotResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=sdwb__pb2.Empty.FromString,
                    response_serializer=sdwb__pb2.Empty.SerializeToString,
            ),
            'StartElection': grpc.unary_unary_rpc_method_handler(
                    servicer.StartElection,
                    request_deserializer=sdwb__pb2.ElectionMessage.FromString,
                    response_serializer=sdwb__pb2.ElectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdwb.BoardCoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sdwb.BoardCoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BoardCoordinatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinBoard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.BoardCoordinatorService/JoinBoard',
            sdwb__pb2.JoinRequest.SerializeToString,
            sdwb__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.BoardCoordinatorService/SendAction',
            sdwb__pb2.ActionRequest.SerializeToString,
            sdwb__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.BoardCoordinatorService/GetSnapshot',
            sdwb__pb2.Empty.SerializeToString,
            sdwb__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.BoardCoordinatorService/Ping',
            sdwb__pb2.Empty.SerializeToString,
            sdwb__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartElection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.BoardCoordinatorService/StartElection',
            sdwb__pb2.ElectionMessage.SerializeToString,
            sdwb__pb2.ElectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClientUpdateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrepareAction = channel.unary_unary(
                '/sdwb.ClientUpdateService/PrepareAction',
                request_serializer=sdwb__pb2.ActionRequest.SerializeToString,
                response_deserializer=sdwb__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.CommitAction = channel.unary_unary(
                '/sdwb.ClientUpdateService/CommitAction',
                request_serializer=sdwb__pb2.ActionRequest.SerializeToString,
                response_deserializer=sdwb__pb2.Empty.FromString,
                _registered_method=True)
        self.AbortAction = channel.unary_unary(
                '/sdwb.ClientUpdateService/AbortAction',
                request_serializer=sdwb__pb2.ActionRequest.SerializeToString,
                response_deserializer=sdwb__pb2.Empty.FromString,
                _registered_method=True)
        self.GetLocalSnapshot = channel.unary_unary(
                '/sdwb.ClientUpdateService/GetLocalSnapshot',
                request_serializer=sdwb__pb2.Empty.SerializeToString,
                response_deserializer=sdwb__pb2.SnapshotResponse.FromString,
                _registered_method=True)


class ClientUpdateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PrepareAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocalSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientUpdateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrepareAction': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareAction,
                    request_deserializer=sdwb__pb2.ActionRequest.FromString,
                    response_serializer=sdwb__pb2.VoteResponse.SerializeToString,
            ),
            'CommitAction': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitAction,
                    request_deserializer=sdwb__pb2.ActionRequest.FromString,
                    response_serializer=sdwb__pb2.Empty.SerializeToString,
            ),
            'AbortAction': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortAction,
                    request_deserializer=sdwb__pb2.ActionRequest.FromString,
                    response_serializer=sdwb__pb2.Empty.SerializeToString,
            ),
            'GetLocalSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocalSnapshot,
                    request_deserializer=sdwb__pb2.Empty.FromString,
                    response_serializer=sdwb__pb2.SnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdwb.ClientUpdateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sdwb.ClientUpdateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientUpdateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PrepareAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.ClientUpdateService/PrepareAction',
            sdwb__pb2.ActionRequest.SerializeToString,
            sdwb__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.ClientUpdateService/CommitAction',
            sdwb__pb2.ActionRequest.SerializeToString,
            sdwb__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.ClientUpdateService/AbortAction',
            sdwb__pb2.ActionRequest.SerializeToString,
            sdwb__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLocalSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdwb.ClientUpdateService/GetLocalSnapshot',
            sdwb__pb2.Empty.SerializeToString,
            sdwb__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
